spring:
  application:
    name: hystrix

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://username:password@localhost:8761/eureka    # 指定注册中心的地址
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  server:
    name: eureka-server