spring:
  application:
    name: api-gateway
server:
  port: 5555
eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://username:password@localhost:8761/eureka
zuul:
  routes:
    hello:
      path: /hello-service/**
      serviceId: hello9092
  filter:
    root: spring-cloud-zuul/filter
    interval: 5
debug: true